[project]
name = "dtrpg-sdk"
version = "0.1.0"
description = "SDK for the DriveThruRPG API"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Paul Schifferer", email = "paul@schifferers.net" }
]
requires-python = ">=3.12.0"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.0",
    "pyrefly>=0.13.0",
    "ruff>=0.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pyrefly]
project-includes = ["src", "tests"]
